### ISSUE TITLE
No model class TaskRecord is created?

### ISSUE THREAD

**Issue by mxavi** [theSteveMitchell/after_party#21]
I don't if I am right, but I haven't seen a TaskRecord class after I have run "rails generate after_party:install" command. Is that a problem?

In addition, after I ran "rails generate after_party:task" command this line was generated: "TaskRecord.create :version => '20151217165103'"

Then I've got 'Can't mass-assign protected attributes: version' error

**Comment by theSteveMitchell** [comment]
You should be able to access it as "AfterParty::TaskRecord"

Can you tell me which version of Rails and this gem you are using?  There was a previously reported issue that should be fixed now with Rails 3.

**Comment by theSteveMitchell** [comment]
Will reopen if the issue persists.

**Comment by chrisdrappier** [comment]
I'm having this issue now. rails 4.2.7.1 and after_party 1.10.0 @theSteveMitchell was there a resolution?
