### ISSUE TITLE
Generators don't show up in Rails 4.2.2

### ISSUE THREAD

**Issue by rishav** [theSteveMitchell/after_party#23]
I have an Rails 4.2.2 app, I followed the instructions in the Gem, did a bundle install. I get the following error:

`Could not find generator 'after_party:install'.`

**Comment by theSteveMitchell** [comment]
I'm not able to replicate with Rails 4.2.2.  

You have in your Gemfile `gem 'after_party'?  (The underscore is important, there is another gem called afterparty with no underscore).

If you could list your versions of ruby, bundler after_party itself that would help.
Also the output of `rails g` and `rake -T` would help.

**Comment by rishav** [comment]
Issues with spring. Had to run "bin/spring stop" before it showed the generators. Thanks

**Comment by rishav** [comment]
Yep. :)
